### PR TITLE
DEV: Refactored DEBUG and DBG to FDRS_DEBUG and FDRS_DBG

### PR DESCRIPTION
**Pull request by Gulpman**
As mentioned in #47 the names DEBUG and DBG prevent the project to compile on PlatformIO.
It also will prevent issues when other libraries will be used in the project as it is likely that DEBUG and DBG may be used there as well.

In addition I removed a duplicate entry from keywords.txt

### CODE REVIEW

**Comment by timmbogner** [comment]
Is DBG() definitely a no-go? I really like the brevity of it and would like to keep it short.

**Comment by Gulpman** [comment]
I think it is not a no-go. Im my opinion it is more about consistency. Therefore I would prefer switching to FDRS_DBG.

**Comment by Devilbinder** [comment]
Common practice to use a project prefix with debug macros. The issue is that everyone likes using `DEBUG` so no-one can use it because it causes conflicts like we see now with #47. Also `DEBUG` is a build reserved macro in many cases.

Example of a widely used repos config system.
https://github.com/Mbed-TLS/mbedtls/blob/a343d34f0d6e11576863bcd626ac966b42f2deb7/include/mbedtls/mbedtls_config.h#L1397

**Comment by timmbogner** [comment]
I support that with the full DEBUG term. It makes a lot of sense and is no issue.

What I'm dragging my feet on is the DBG() function. If DBG is commonly used, can we find a three letter term that isn't? I like it short, sorry if this is sort of petty. I have just always liked how easy it makes it to add verbosity.

I won't die on this hill, but I did want to make a stand.

**Pull request merged**
