### PR TITLE
Add MQTT port selection and MQTT user/password auth support

### PR DESCRIPTION
**Pull request by thefeiter**
First of all: Great Project! Got it up and running with spare parts laying around in under an hour.

In my setup, I want to use an MQTT broker on my server which requires authentication, so I added a few lines to be able to set MQTT user credentials.
Also I added an option to select the port of the broker.

It works in my test setup.

Maybe it can be simplified.

### CODE REVIEW

**Comment by timmbogner** [comment]
Yo, thanks! I appreciate the help! The dev branch has some drastic changes happening, so I think that explains the conflicts? I will have a look on Monday and possibly just pull this to the main branch while the new version is under testing/construction.

**Comment by Devilbinder** [comment]
I unfortunately can't see what is causing the conflict. This code does not seem to affect the changes that I have made. Specifically left the current gateway examples alone until I have conformation that the Universal Gateway example is working.

**Comment by Devilbinder** [comment]
Resolved the conflict on https://github.com/Devilbinder/Farm-Data-Relay-System/tree/dev2
@thefeiter you should just need to merge my branch into yours to resolve the conflict.

**Comment by thefeiter** [comment]
Done, thanks!

**Pull request merged**
